name: ucl_lung_cancer_models
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scikit-learn=0.24.2
  - numpy=1.23
  - lightgbm
  - pandas
  - numba
  - catboost
  - optuna
  - pip
  - pip:
    - combo
    - cloudpickle
    - sklearn-pandas
    - gunicorn
    - loguru
    - uvicorn
    - fastapi
    - jupyter
