name: ucl_lung_cancer_models
channels:
  - sebp
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scikit-learn=0.24.2
  - numpy<1.20
  - lifelines
  - scikit-survival
  - joblib
  - setuptools
  - blas
  - llvm-openmp
  - lightgbm
  - shap
  - py-xgboost
  - pytorch=1.13.0
  - optuna
  - pandas
  - numba
  - catboost
  - matplotlib
  - seaborn
  - pip
  - pip:
    - kaleido
    - plotly
    - streamlit
    - combo
    - cloudpickle
    - ganite
    - lime
    - jupyterlab
    - notebook
    - sklearn-pandas
    - xgbse
    - gunicorn
    - loguru
    - psutil
    - pycox
    - pydantic
    - pymfe
    - redis
    - uvicorn
    - bandit
    - black
    - black-nb
    - darglint
    - doc8
    - flake8
    - isort
    - nbconvert
    - nbformat
    - pytest
    - pytest-benchmark
    - pytest-cov
    - pytest-xdist[psutil]
    - pytest-xprocess
    - fastapi
    - html5lib
    - pykeops
    - geomloss